### ISSUE TITLE
is this an app, where u can stole anybody's password to facebook?

### ISSUE THREAD

**Issue by Doni2006120** [codesandbox/static-template#162]
if yes, then fu all

**Comment by youngchief-btw** [comment]
N O, That is not what Codesandbox does. It is an online code editor.

**Comment by andrasbacsai** [comment]
Codesandbox is a online code editor, where you can create & share web applications with anybody.

Unfortunately, there are a lot of phishing sites/apps created with codesandbox. We are constantly fighting against them, with deletion & banning.

If you find a suspicious site, please report to us so we take the necessary steps.

**Comment by Doni2006120** [comment]
hi!
Now i feel a little more reassured, thank you for the explain. I got this
from a messenger user: https://xowgj.csb.app/#0.9534734818466275, with this
sharing method:

**Comment by Doni2006120** [comment]
I hope you can do something about it!

Mateus <matematek550@gmail.com> ezt írta (időpont: 2020. jún. 6., Szo,
13:35):

> hi!
> Now i feel a little more reassured, thank you for the explain. I got this
> from a messenger user: https://xowgj.csb.app/#0.9534734818466275, with
> this sharing method:
>
>

**Comment by andrasbacsai** [comment]
We removed that sandbox. Thanks for notifying us.

**Comment by Doni2006120** [comment]
Thanks for the fast solution!

Andras Bacsai <notifications@github.com> ezt írta (időpont: 2020. jún. 6.,
Szo, 21:51):
